# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 22:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 21, 22, 55, 48, 975342, tzinfo=utc)),
        ),
    ]
