# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170721_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
