# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 23:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 23, 54, 13, 819311, tzinfo=utc)),
        ),
    ]
